enum BandsyResponseCodes {
  ERROR_HANDLER_ERROR,
  UNKNOWN_ERROR,
  VALIDATION_ERROR,
  CLIENT_ERROR,
  SERVER_ERROR,
  DUPLICATE_EMAIL,
  INVALID_ACCOUNT,
  INVALID_VERIFICATION,
  INVALID_CREDENTIALS,
  INVALID_MFA,
  INVALID_TOKEN,
  FORBIDDEN,
  UNAUTHORISED,
  RATELIMITED,
}

export {
  // eslint-disable-next-line import/prefer-default-export
  BandsyResponseCodes,
};
